# Test Values
image:
  registry: ghcr.io
  repository: home-assistant/home-assistant
ports:
  - name: http
    containerPort: 8120
    protocol: TCP
extraVolumes:
  - name: config
    persistentVolumeClaim:
      claimName: homeassistant-config-claim
extraVolumeMounts:
  - name: config
    mountPath: /config