apiVersion: v3
description: Invoice Ninja
name: invoiceninja
version: 0.0.6
appVersion: 0.0.6
sources:
  - 'https://github.com/scottdotau/home-charts'
  - 'https://github.com/invoiceninja/invoiceninja'
maintainers:
  - name: scottdot
    email: scawtee@protonmail.com
dependencies:
  - name: hull
    version: 1.29.7
    repository: 'https://vidispine.github.io/hull'
