# Invoice Ninja
image:
  registry: docker.io
  repository: invoiceninja/invoiceninja
  tag: 5
  imagePullPolicy: IfNotPresent
ports:
  - name: http
    containerPort: 9000
    protocol: TCP
envVars:
  - name: APP_ENV
    value: 'production'
  - name: APP_DEBUG
    value: '0'
  - name: APP_URL
    value: 'yourdomain'
  - name: APP_KEY
    value: 'S0meRandomStringSomeRandomString'
  - name: APP_CIPHER
    value: 'AES-256-CBC'
  - name: TRUSTED_PROXIES
    value: '10.0.0.0/8'
  - name: DB_TYPE
    value: 'mysql'
  - name: DB_USERNAME
    value: 'root'
  - name: DB_PASSWORD
    value: 'ninja'
  - name: DB_HOST
    value: '127.0.0.1'
  - name: DB_DATABASE
    value: 'ninja'
  - name: MAIL_HOST
    value: mailserver
  - name: MAIL_DRIVER
    value: smtp
  - name: MAIL_FROM_NAME
    value: 'InvoiceNinja'
  - name: MAIL_FROM_ADDRESS
    value: 'finance@yourdomain'
sidecars:
  - name: mysql
    image: mariadb:11
    imagePullPolicy: IfNotPresent
    args: ['--default-authentication-plugin=mysql_native_password']
    env:
      - name: MYSQL_DATABASE
        value: 'ninja'
      - name: MYSQL_ROOT_PASSWORD
        value: 'ninja'
    ports:
      - containerPort: 3306
        name: mysql
  - name: redis
    image: mariadb:11
    imagePullPolicy: IfNotPresent
    args: ['--default-authentication-plugin=mysql_native_password']
    env:
      - name: MYSQL_DATABASE
        value: 'ninja'
      - name: MYSQL_ROOT_PASSWORD
        value: 'ninja'
    ports:
      - containerPort: 3306
        name: mysql